name: zkApp tests
on:
  push:
  pull_request:
  workflow_dispatch: {}
jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node: [18, 20]
        os: [ubuntu-latest]
    steps:
      - name: Set up NodeJS
        uses: meta-introspector/setup-node@main        
        with:
          node-version: ${{ matrix.node }}
      - name: Git checkout
        uses: meta-introspector/checkout@v4
      - name: NPM ci, build, & test
        working-directory: ./contracts
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
